# Assignment-1: NumPy

1. Create a null vector of size 10 but the fifth value which is 1.
2. Create a vector with values ranging from 10 to 49.
3. Create a 3x3 matrix with values ranging from 0 to 8
4. Find indices of non-zero elements from [1,2,0,0,4,0]
5. Create a 10x10 array with random values and find the minimum and maximum values.
6. Create a random vector of size 30 and find the mean value.


In [1]:
# 1. Create a null vector of size 10 but the fifth value which is 1.
import numpy as np
z = np.zeros(10)
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [2]:
# 2. Create a vector with values ranging from 10 to 49.
import numpy as np
z = np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [3]:
# 3. Create a 3x3 matrix with values ranging from 0 to 8
import numpy as np
z = np.arange(9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
# 4. Find indices of non-zero elements from [1,2,0,0,4,0]
import numpy as np
z = np.nonzero([1,2,0,0,4,0])
print(z)

(array([0, 1, 4], dtype=int64),)


In [7]:
# 5. Create a 10x10 array with random values and find the minimum and maximum values.
import numpy as np
z = np.random.random((10,10))
zmin, zmax = z.min(), z.max()
print('Min:',zmin,'Max:',zmax)

Min: 0.012801092566109729 Max: 0.9880239124651329


In [8]:
# 6. Create a random vector of size 30 and find the mean value.
import numpy as np
z = np.random.random(30)
m = z.mean()
print('Mean:',m)

Mean: 0.5274593845504755
